require "example_long_hand_array_flattener/version"
require "example_long_hand_array_flattener/array_flattener_error"
require "example_long_hand_array_flattener/array_flattener"

module ExampleLongHandArrayFlattener
end
